Add friends & likes
AntonFeklichev/java-filmorate pull request #3
Opened 2022-09-07 11:14 UTC by AntonFeklichev

2022-09-07 11:16 UTC, AntonFeklichev commented
<img width="446" alt="Screen Shot 2022-09-07 at 2 15 08 PM" src="https://user-images.githubusercontent.com/102986103/188865377-da8bb480-5d13-4042-a391-bba4e2efb1d6.png">
Подскажите пожалуйста, какой из этих способов слияния самый безопасный?

2022-09-07 19:28 UTC, sergeymamonov requested changes
Можно всю валидацию вынести в сервисный слой. В нем же и присваивать id. Так будет чище с архитектурной точки зрения. Так как слой сервиса занят обработкой, валидацией и так далее. А слой стоража хранением и так далее.

2022-09-07 19:28 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/handler/FilmControllerExceptionHandler.java
> +    }
Ошибок может быть больше, 404, 409, 500.

2022-09-07 19:28 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exception/UnknownFilmException.java
> +public class UnknownFilmException extends RuntimeException {
Название ошибки ничего не говорит. Плюс для юзера точно такой же класс. Во-первых, их можно объединить, во-вторых дать более информативное название (DataAlreadyExistException, DataNotFoundException и так далее).

2022-09-07 19:28 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/handler/FilmControllerExceptionHandler.java
> +    }
Не обязательно делать два обработчика ошибок. Если ошибки будут общими, то и обработчик можно сделать только один.

2022-09-10 07:52 UTC, sergeymamonov commented
> <img alt="Screen Shot 2022-09-07 at 2 15 08 PM" width="446" src="https://user-images.githubusercontent.com/102986103/188865377-da8bb480-5d13-4042-a391-bba4e2efb1d6.png">
> 
> Подскажите пожалуйста, какой из этих способов слияния самый безопасный?

В случае, когда вы один работаете над проектом, не думаю, что будут какие-то конфликты при слиянии. Конфликты бывают, когда работают несколько человек над одними и теми же участками кода. В реальных проектах конфликты при слиянии это обычное дело. В идеи их удобно разрешать.

Что касается предлагаемых вариантов, то это больше к тому, как будет оформлено слияние. То есть это не про решение конфликтов. Если правильно понимаю, что вы подразумеваете под безопаснотью избежание конфликтов, то конфликты возникают не от способа слияния, а от того, что несколько человек меняют один и тот же код.

2022-09-10 13:33 UTC, sergeymamonov commented
Предлагаю все-таки добавить в обработчик ошибок проверку 400 ошибки и 409 ошибки. А перед записью в мапу проверять, нет ли в мапе уже объекта с id, как у объекта, который будет записываться. И если объект в мапе уже есть, то кидать ошибку (ошибка 409)

2022-09-10 13:33 UTC, sergeymamonov approved these changes

2022-09-27 19:43 UTC, merged